routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\CommentController;



Route::get('/', function () {
    return view('welcome');
});

Route::get('/hello', function () {
    return view('greeting', ['name' => $user = Auth::user()->name]);
} )->middleware('auth');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/news', 'UserController@index')->name('news');

Route::get('/news', 'ArticleController@index')->name('news');

Route::get('profile', 'UserController@profile')->middleware('auth');

Route::resource('posts','PostController')->middleware('auth');

Route::resource('comments', 'CommentController')->middleware('auth');

Route::post('profile', 'UserController@update_avatar')->middleware('auth');

Route::post('/image/upload', 'UserController@store')->name('upload-image');

Route::get('users/{edit}', 'UserController@edit')->name('users.edit');

Route::put('users/{user}/update',  ['as' => 'users.update', 'uses' => 'UserController@update']);

// Route::get('/posts')

Auth::routes();

resources/views/greeting.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                Hello, {{ $name }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                    <a href="{{ route('posts.show', $user ?? '') }}">Show Posts</a>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/news.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                  
                @foreach($articles as $key => $data)
                    <tr>
                        AuthorID:  <th>{{$data->id}}</th><br>
                        Author name:  <th>{{$data->title}}</th><br>
                         New:  <th>{{$data->content}}</th><br>
                    </tr>
                    @endforeach

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/profile.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        @if ($message = Session::get('success'))

        <div class="alert alert-success alert-block">

            <button type="button" class="close" data-dismiss="alert">×</button>

            <strong>{{ $message }}</strong>

        </div>

        @endif

        @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif
    </div>
    <div class="row justify-content-center">

        <div class="profile-header-container">
            <div class="profile-header-img">
                <img class="rounded-circle" src="{{ asset('images/'.$user->avatar) }}" width="250px" height="250px" />

                <div class="rank-label-container">
                    <span class="label label-default rank-label"><h2>{{$user->name}}</h2></span>
                    <li><a href="{{ route('users.edit', $user ?? '') }}">Edit Profile</a></li>
                </div>
            </div>
        </div>

    </div>



    <div class="row justify-content-center">
        <form action="{{ route('upload-image') }}" enctype="multipart/form-data" method="post" enctype="multipart/form-data">
           {{ @csrf_field() }} 
            <div class="form-group">
                <input type="file" class="form-control-file" name="avatar" id="avatarFile" aria-describedby="fileHelp">
                <small id="fileHelp" class="form-text text-muted">Please upload a valid image file. Size of image should not be more than 2MB.</small>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>
@endsection