routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\CommentController;



Route::get('/', function () {
    return view('welcome');
});

Route::get('/hello', function () {
    return view('greeting', ['name' => $user = Auth::user()->name]);
} )->middleware('auth');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/news', 'UserController@index')->name('news');

Route::get('/news', 'ArticleController@index')->name('news');

Route::get('profile', 'UserController@profile')->middleware('auth');

Route::resource('posts','PostController')->middleware('auth');

Route::resource('comments', 'CommentController')->middleware('auth');

Route::post('profile', 'UserController@update_avatar')->middleware('auth');

Route::post('/image/upload', 'UserController@store')->name('upload-image');

Route::get('users/{edit}', 'UserController@edit')->name('users.edit');

Route::put('users/{user}/update',  ['as' => 'users.update', 'uses' => 'UserController@update']);

// Route::get('/posts')

Auth::routes();

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
    use SoftDeletes;

    protected $dates = ['deleted_at'];

    /**
     * The attributes that are mass assignable.
     * 
     * @var array
     */

    protected $fillable = ['title', 'body'];

    /**
     * The has Many Relationship
     * 
     * @var array
     */

    public function comments()
    {
        return $this->hasMany(Comment::class)->whereNull('parent_id');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\User;
use Illuminate\Support\Facades\Storage;


class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {
        $posts = Post::all();

        return view('posts.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */

    private function hashImageName($image)
    {
        return md5($image->getClientOriginalName() . uniqid('weband')) . '.' . $image->getClientOriginalExtension();
    }

    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
            'body' => 'required',
            'image' => 'required|image|mimes:jpeg,png,jpg,gif|max:2048',
        ]);

        $post = new Post;
        $post->title = $request->title;
        $post->body = $request->body;

        //Check if image is presented in the request and it's valid
        if ($request->hasFile('image') && $request->image->isValid()) {
            $image = $request->image;
            $image_name = $this->hashImageName($image);

            //store the image in the filesystem
            Storage::disk('images')->putFileAs('', $image, $image_name);

            $post->image = $image_name;
        }

        $post->save();

        return redirect()->route('posts.index')

            ->with('success', 'Post created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        return view('posts.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        return view('posts.edit', compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        $request->validate([
            'title' => 'required',
            'body' => 'required',
        ]);

        $post->update($request->all());

        return redirect()->route('posts.index')
            ->with('success', 'Post updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        $post->delete();

        return redirect()->route('posts.index')
            ->with('success', 'Post deleted successfully');
    }
}

resources/views/posts/commentsDisplay.blade.php
@extends('layouts.app')

@section('content')

@foreach($comments as $comment)
    <div class="display-comment"> 
        <strong>{{ $comment->user->name }}</strong>
        <p>{{ $comment->body }}</p>
        <a href="" id='reply'></a>
        <form method='POST' action="{{ route('comments.store') }}">
            @csrf
            <div class='form-group'>
                <input type="text" name='body' class='form-control' >
                <input type="hidden" name='post_id' value='{{ $post_id }}'>
                <input type="hidden" name="parent_id" value="{{ $comment->id }}">
            </div>
            <div class='form-group'>
                <input type="submit" class='btn btn-warning' value='Reply'>
            </div>
        </form>
    @include('posts.commentsDisplay', ['comments' => $comment->replies])
    </div>
@endforeach

resources/views/posts/create.blade.php
@extends('layouts.app')
@section('content')

<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Create Post
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('posts.store') }}" enctype="multipart/form-data">
          <div class="form-group">
              @csrf
              <label for="title">Title:</label>
              <input type="text" class="form-control" name="title" id="title" />
          </div>
          <div class="form-group">
              <label for="price">Body:</label>
              <textarea name="body" id="body" class="form-control"></textarea>
            
          </div>

          <div class="form-group">
              <label for="price">Image:</label>
              <input type="file" name="image">
            
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
      </form>
  </div>
</div>
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')

@section('content')

<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Edit Post
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('posts.update', $post->id) }}">
                @csrf

        @method('PUT')

        <div class="form-group">
          <label for="title">Title:</label>
          <input type="text" class="form-control" name="title" id="post_title" value={{ $post->title }} />
        </div>
        <div class="form-group">
          <label for="price">Body:</label>
          <textarea name="body" id="post_body" class="form-control">{{ $post->body }}</textarea>
        </div>
        
        <button type="submit" class="btn btn-primary">Update</button>
      </form>
  </div>
</div>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('content')

<style>
  .uper {
    margin-top: 40px;
  }
</style>

<div class="card uper">

  <div class="card-header">
    <a class="btn btn-primary" href="{{ route('posts.create') }}"> Create New Post</a>
  </div>

  <div class="card-body">
    @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}
    </div><br />
    @endif


    <table class="table table-striped">
      <thead>
        <tr>
          <td>Image</td>
          <td>ID</td>
          <td>Post Title</td>
          <td>Post Body</td>
          <td colspan="3">Action</td>
        </tr>
      </thead>
      <tbody>
        @foreach($posts as $post)
        <tr>
          <td>
            <img class="rounded-circle" src="{{ asset('images/'.$post->image) }}" width="30px" height="30px" />
          </td>
          <td>{{$post->id}}</td>
          <td>{{$post->title}}</td>
          <td>{{$post->body}}</td>
          <td><a href="{{ route('posts.edit',$post->id)}}" class="btn btn-primary">Edit</a></td>
          <td><a class="btn btn-primary" href="{{ route('posts.show',$post->id) }}">Show</a></td>
    
          <td>
            <form action="{{ route('posts.destroy', $post->id)}}" method="post">
              @csrf
              @method('DELETE')
              <button class="btn btn-danger" type="submit">Delete</button>
            </form>
          </td>
        </tr>
        
        @endforeach
      </tbody>
    </table>
  </div>
</div>

@endsection

resources/views/posts/show.blade.php
@extends('layouts.app')

@section('content')

<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    View Post


    <a class="btn btn-primary" href="{{ route('posts.index') }}"> Back</a>


  </div>
  <div class="card-body">
    <div class="row">

      <div class="col-xs-12 col-sm-12 col-md-12"> 
    
      <div>
          <img class="rounded-circle" src="{{ asset('images/'.$post->image) }}" width="40px" height="40px" />
        </div>
        <br>

        <div class="form-group">


          <strong>Title:</strong>

          {{ $post -> title}}

        </div>

      </div>


      <div class="col-xs-12 col-sm-12 col-md-12">

        <div class="form-group">

          <strong>Body:</strong>

          {{ $post -> body }}

        </div>

      </div>

      <div class="col-xs-12 col-sm-12 col-md-12">

        <div class="form-group">

          <strong>Comments</strong>

          @include('posts.commentsDisplay', ['comments' => $post->comments, 'post_id' => $post->id])

        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">

          <div class="form-group">

            <strong>Add comment</strong>

            <form method='POST' action="{{ route('comments.store') }}">
              @csrf
              <div class="form-group">
                <textarea class="form-control" name="body"></textarea>
                <input type="hidden" name='post_id' value="{{ $post->id }}">
              </div>
              <div class="form-group"></div>
              <input type="submit" class="btn btn-success" value="Add comment">
            </form>
          </div>

        </div>

      </div>

    </div>
  </div>
  @endsection